import { MODEL_ROLES } from "../models.js";
import type { RoutingConfig } from "./types.js";

const LIGHT = MODEL_ROLES.light;
const STRONG = MODEL_ROLES.strong;

export const DEFAULT_ROUTING_CONFIG: RoutingConfig = {
  version: "2.0",

  classifier: {
    llmModel: LIGHT,
    llmMaxTokens: 10,
    llmTemperature: 0,
    promptTruncationChars: 500,
    cacheTtlMs: 3_600_000,
  },

  scoring: {
    tokenCountThresholds: { simple: 50, complex: 500 },

    codeKeywords: [
      "function",
      "class",
      "import",
      "def",
      "select",
      "async",
      "await",
      "const",
      "let",
      "var",
      "return",
      "debug",
      "fix",
      "refactor",
      "```",
      "函数",
      "类",
      "导入",
      "定义",
      "查询",
      "异步",
      "等待",
      "常量",
      "变量",
      "返回",
      "関数",
      "クラス",
      "функция",
      "класс",
      "funktion",
      "clase",
      "función",
      "função",
      "함수",
      "دالة",
    ],
    reasoningKeywords: [
      "prove",
      "theorem",
      "derive",
      "step by step",
      "chain of thought",
      "formally",
      "mathematical",
      "proof",
      "logically",
      "证明",
      "定理",
      "推导",
      "逐步",
      "思维链",
      "形式化",
      "数学",
      "逻辑",
      "証明",
      "導出",
      "доказать",
      "доказательств",
      "теорема",
      "пошагово",
      "beweisen",
      "beweis",
      "demostrar",
      "provar",
      "증명",
      "إثبات",
    ],
    simpleKeywords: [
      "what is",
      "define",
      "translate",
      "hello",
      "yes or no",
      "capital of",
      "how old",
      "who is",
      "when was",
      "summarize",
      "briefly",
      "什么是",
      "定义",
      "翻译",
      "你好",
      "总结",
      "简要",
      "とは",
      "定義",
      "翻訳",
      "что такое",
      "перевести",
      "was ist",
      "übersetze",
      "qué es",
      "traducir",
      "o que é",
      "번역",
      "ما هو",
    ],
    technicalKeywords: [
      "algorithm",
      "optimize",
      "architecture",
      "distributed",
      "kubernetes",
      "microservice",
      "database",
      "infrastructure",
      "debug",
      "tests",
      "test failures",
      "failing tests",
      "across files",
      "multiple files",
      "related files",
      "root cause",
      "fix",
      "refactor",
      "verify",
      "everything passes",
      "算法",
      "优化",
      "架构",
      "分布式",
      "微服务",
      "数据库",
      "基础设施",
      "アルゴリズム",
      "архитектура",
      "algorithmus",
      "algoritmo",
      "아키텍처",
    ],
    creativeKeywords: [
      "story",
      "poem",
      "compose",
      "brainstorm",
      "creative",
      "imagine",
      "write a",
      "故事",
      "诗",
      "创作",
      "头脑风暴",
      "创意",
      "想象",
      "写一个",
      "物語",
      "история",
      "geschichte",
      "historia",
      "이야기",
      "قصة",
    ],
    imperativeVerbs: [
      "build",
      "create",
      "implement",
      "design",
      "develop",
      "construct",
      "generate",
      "deploy",
      "configure",
      "set up",
      "构建",
      "创建",
      "实现",
      "设计",
      "开发",
      "生成",
      "部署",
      "配置",
      "设置",
      "実装",
      "создать",
      "реализовать",
      "erstellen",
      "implementar",
      "구현",
      "تنفيذ",
    ],
    constraintIndicators: [
      "under",
      "at most",
      "at least",
      "within",
      "no more than",
      "o(",
      "maximum",
      "minimum",
      "limit",
      "budget",
      "不超过",
      "至少",
      "最多",
      "最大",
      "最小",
      "限制",
      "预算",
      "максимум",
      "mindestens",
      "como máximo",
      "최대",
    ],
    outputFormatKeywords: [
      "json",
      "yaml",
      "xml",
      "table",
      "csv",
      "markdown",
      "schema",
      "format as",
      "structured",
      "表格",
      "格式化为",
      "结构化",
      "структурированный",
      "tabelle",
      "tabla",
      "테이블",
    ],
    referenceKeywords: [
      "above",
      "below",
      "previous",
      "following",
      "the docs",
      "the api",
      "the code",
      "earlier",
      "attached",
      "上面",
      "下面",
      "之前",
      "接下来",
      "文档",
      "代码",
      "附件",
      "上記",
      "выше",
      "dokumentation",
      "documentación",
      "문서",
    ],
    negationKeywords: [
      "don't",
      "do not",
      "avoid",
      "never",
      "without",
      "except",
      "exclude",
      "no longer",
      "不要",
      "避免",
      "从不",
      "没有",
      "除了",
      "排除",
      "しないで",
      "нельзя",
      "vermeide",
      "evitar",
      "하지 마",
    ],
    domainSpecificKeywords: [
      "quantum",
      "fpga",
      "vlsi",
      "risc-v",
      "asic",
      "photonics",
      "genomics",
      "proteomics",
      "topological",
      "homomorphic",
      "zero-knowledge",
      "lattice-based",
      "量子",
      "光子学",
      "基因组学",
      "蛋白质组学",
      "拓扑",
      "同态",
      "零知识",
      "格密码",
      "квантовый",
      "quanten",
      "cuántico",
      "양자",
    ],
    agenticTaskKeywords: [
      "read file",
      "read the file",
      "look at",
      "check the",
      "open the",
      "edit",
      "modify",
      "update the",
      "change the",
      "write to",
      "create file",
      "execute",
      "deploy",
      "install",
      "npm",
      "pip",
      "compile",
      "after that",
      "and also",
      "once done",
      "step 1",
      "step 2",
      "fix",
      "debug",
      "until it works",
      "keep trying",
      "iterate",
      "make sure",
      "verify",
      "confirm",
      "读取文件",
      "查看",
      "打开",
      "编辑",
      "修改",
      "更新",
      "创建",
      "执行",
      "部署",
      "安装",
      "第一步",
      "第二步",
      "修复",
      "调试",
      "直到",
      "确认",
      "验证",
      "leer archivo",
      "editar",
      "modificar",
      "actualizar",
      "ejecutar",
      "desplegar",
      "instalar",
      "verificar",
      "파일 읽기",
      "편집",
      "수정",
      "업데이트",
      "실행",
      "확인",
    ],

    dimensionWeights: {
      tokenCount: 0.08,
      codePresence: 0.15,
      reasoningMarkers: 0.18,
      technicalTerms: 0.1,
      creativeMarkers: 0.05,
      simpleIndicators: 0.02,
      multiStepPatterns: 0.12,
      questionComplexity: 0.05,
      imperativeVerbs: 0.03,
      constraintCount: 0.04,
      outputFormat: 0.03,
      referenceComplexity: 0.02,
      negationComplexity: 0.01,
      domainSpecificity: 0.02,
      agenticTask: 0.04,
      codebaseDebugging: 0.5,
    },
    tierBoundaries: {
      simpleMedium: 0,
      mediumComplex: 0.3,
      complexReasoning: 0.8,
    },
    confidenceSteepness: 12,
    confidenceThreshold: 0.8,
  },

  tiers: {
    SIMPLE: { primary: LIGHT, fallback: [] },
    MEDIUM: { primary: LIGHT, fallback: [STRONG] },
    COMPLEX: { primary: STRONG, fallback: [] },
    REASONING: { primary: STRONG, fallback: [] },
  },

  agenticTiers: {
    SIMPLE: { primary: LIGHT, fallback: [] },
    MEDIUM: { primary: LIGHT, fallback: [STRONG] },
    COMPLEX: { primary: STRONG, fallback: [] },
    REASONING: { primary: STRONG, fallback: [] },
  },

  premiumTiers: {
    SIMPLE: { primary: STRONG, fallback: [] },
    MEDIUM: { primary: STRONG, fallback: [] },
    COMPLEX: { primary: STRONG, fallback: [] },
    REASONING: { primary: STRONG, fallback: [] },
  },

  ecoTiers: {
    SIMPLE: { primary: LIGHT, fallback: [] },
    MEDIUM: { primary: LIGHT, fallback: [] },
    COMPLEX: { primary: STRONG, fallback: [] },
    REASONING: { primary: STRONG, fallback: [] },
  },

  overrides: {
    maxTokensForceComplex: 128_000,
    structuredOutputMinTier: "MEDIUM",
    ambiguousDefaultTier: "MEDIUM",
  },
};
